name: Prime Data Hub

on:
  push:
    branches: [ master, production ]

defaults:
  run:
    working-directory: prime-router

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set Environment Variables
        run: |
               if [ "$GITHUB_REF" == "refs/heads/production" ]
               then
                   echo "Deploying to the production environment."
                   echo >> $GITHUB_ENV RESOURCE_GROUP=prime-data-hub-prod
                   echo >> $GITHUB_ENV ACR_REPO=pdhprodcontainerregistry.azurecr.io
                   echo >> $GITHUB_ENV PREFIX=pdhprod
                   echo >> $GITHUB_ENV POSTGRESQL_USER=${{ secrets.POSTGRESQL_PROD_USER }}
                   echo >> $GITHUB_ENV POSTGRESQL_PWD=${{ secrets.POSTGRESQL_PROD_PWD }}
                   echo >> $GITHUB_ENV PRIME_ENVIRONMENT=prod
                   echo >> $GITHUB_ENV SFTP_CREDS=${{ secrets.SFTP_PROD_CREDS }}
                   echo >> $GITHUB_ENV REDOX_SECRET=${{ secrets.REDOX_PROD_SECRET }}
               else
                   echo "Deploying to the test environment."
                   echo >> $GITHUB_ENV RESOURCE_GROUP=prime-data-hub-test
                   echo >> $GITHUB_ENV ACR_REPO=pdhtestcontainerregistry.azurecr.io
                   echo >> $GITHUB_ENV PREFIX=pdhtest
                   echo >> $GITHUB_ENV POSTGRESQL_USER=${{ secrets.POSTGRESQL_TEST_USER }}
                   echo >> $GITHUB_ENV POSTGRESQL_PWD=${{ secrets.POSTGRESQL_TEST_PWD }}
                   echo >> $GITHUB_ENV PRIME_ENVIRONMENT=test
                   echo >> $GITHUB_ENV SFTP_CREDS=${{ secrets.SFTP_TEST_CREDS }}
                   echo >> $GITHUB_ENV REDOX_SECRET=${{ secrets.REDOX_STAGING_SECRET }}
               fi
               env

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        with:
          postgresql version: 11
          postgresql db: prime_data_hub
          postgresql user: ${{ env.POSTGRESQL_USER }}
          postgresql password: ${{ env.POSTGRESQL_PWD }}
       
      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
           java-version: 11
      
      - name: Build Maven Package
        run: mvn -B clean package --file pom.xml

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{ env.ACR_REPO }}/${{ env.PREFIX }}:latest
      
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL_CREDS }}
        
      - name: ACR Login
        run: az acr login --name ${{ env.ACR_REPO }}
          
      - name : Push Docker Image
        run: docker push ${{ env.ACR_REPO }}/${{ env.PREFIX }}:latest

      - name: Restart Azure Functions App
        run: az functionapp restart --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.PREFIX }}-functionapp

      - name: Set SFTP Environment Variables
        run: |
              az functionapp config appsettings set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.PREFIX }}-functionapp \
              --settings PRIME_ENVIRONMENT=${{ env.PRIME_ENVIRONMENT }} ${{ env.SFTP_CREDS }}

      - name: Set Redox Environment Variables
        run: |
              az functionapp config appsettings set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.PREFIX }}-functionapp \
              --settings REDOX_SECRET=${{ env.REDOX_SECRET }} 
