openapi: 3.0.0
info:
  title: Prime Data Hub
  description: A router of public health data from multiple senders and receivers
  contact:
    name: USDS at Centers for Disease Control and Prevention
    url: https://open.cdc.gov
    email: usds@cdc.gov
  version: 0.1.0-oas3
paths:
  /reports:
    post:
      summary: Post a report to the data hub
      parameters:
        - in: query
          name: client
          description: The client's name (eg. `simple_report`)
          schema:
            type: string
          required: true
        - in: query
          name: option
          description: Optional processing modes
          required: false
          schema:
            type: string
            enum:
              - None
              - ValidatePayload
              - CheckConnections
              - SkipSend
              - SendTrainingFlag
              - SendDebugFlag
        - in: header
          name: x-functions-key
          description: The Azure function key for the end-point
          schema:
            type: string
          required: true
      requestBody:
        description: The public health information being routed
        required: true
        content:
          text/csv:
            schema:
              type: string
            example:
              header1, header2

              value1, value2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '201':
          description: Created. A report was created, but items may have been rejected.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '400':
          description: Invalid request. No report created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        '500':
          description: Internal Server Error
components:
  schemas:
    Report:
      type: object
      required:
        - "errors"
        - "warnings"
      properties:
        id:
          description: the id for the report assigned by the Hub
          type: string
        itemCount:
          description: the number of items in the report that have been accepted
          type: integer
          format: int32
        destinations:
          description: a description of where the report is being sent to
          type: array
          items:
            type: string
        rejected:
          description: a list of item row indexes that were rejected in the report
          type: array
          items:
            type: integer
            format: int32
        errors:
          description: a list of error descriptions that caused the entire report to fail or an item in the report to fail
          type: array
          items:
            type: string
        warnings:
          description: a list of warnings about the newly created report
          type: array
          items:
            type: string
